#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Turn off incompatible services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ sut_incompatible_services | split(',') | reject('==', '') }}"
  failed_when: false
  async: 100
  poll: 1

