#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

  - name: copy registry cert to workers
    include_role:
      name: registry
      tasks_from: install
    when:
    - k8s_enable_registry | bool
    - not (k8s_enable_csp_registry | bool)

  - name: Join workers
    include_role:
      name: kubeadm
      tasks_from: join
    when:
    - install_k8s
    - is_a_unique_worker_or_a_controller

  - name: wait for all nodes ready
    shell:
      cmd: |
        timeout 600s bash -c "while ! kubectl wait --for=condition=Ready node \$(kubectl get nodes -o='custom-columns=name:.metadata.name,ip:.status.addresses[?(@.type==\"InternalIP\")].address' --no-headers | grep -F '{{ private_ip }}' | cut -f1 -d' ') --timeout 30s; do sleep 1s; done"
      executable: /bin/bash
    delegate_to: "{{ ('controller' in groups) | ternary('controller-0','localhost') }}"

