#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

    - name: setup port forwarding
      shell:
        cmd: |
          nohup ssh -p {{ ansible_port | default(22) }} {{ ansible_user }}@{{ ansible_host }} -fNL {{ local_daemon_url }}:/var/run/docker.sock -i {{ ansible_private_key_file }} > /dev/null 2>&1 &
          disown
        executable: /bin/bash
      delegate_to: localhost
      become: false

    - name: inspect local images
      command: "docker image inspect {{ item.key }}"
      register: inspect_l
      with_dict: "{{ wl_docker_images }}"
      become: true
      delegate_to: localhost
      ignore_errors: true

    - name: copy daemon images to daemon
      command: "skopeo copy --src-tls-verify={{ item.item.value }} --dest-daemon-host=http://localhost:12222 docker-daemon:{{ item.item.key }} docker-daemon:{{ item.item.key }}"
      environment:
        ALL_PROXY: ""
        all_proxy: ""
      register: copy_result
      until: copy_result.rc == 0
      retries: 10
      delay: 5
      when: item.rc == 0
      loop: "{{ inspect_l.results }}"
      delegate_to: localhost
      become: yes

    - name: copy registry images to daemon
      command: "skopeo copy {{ skopeo_options | default('') }} --src-tls-verify={{ item.item.value }} --dest-daemon-host=http://{{ local_daemon_url }} docker://{{ item.item.key }} docker-daemon:{{ item.item.key }}"
      environment:
        ALL_PROXY: ""
        all_proxy: ""
      register: copy_result
      until: copy_result.rc == 0
      retries: 10
      delay: 5
      when: item.rc != 0
      loop: "{{ inspect_l.results }}"
      delegate_to: localhost
      become: yes

    - name: inspect remote images
      command: "docker image inspect {{ item.item.key }}"
      register: inspect_r
      when: item.rc != 0
      loop: "{{ inspect_l.results }}"
      become: false
      ignore_errors: true

    - name: append build_commit_id and build_branch to workload-config.yaml
      blockinfile:
        path: "{{ wl_logs_dir }}/workload-config.yaml"
        marker: "# {mark} BUILD CONFIG"
        content: |
          build_commit_id: "{{ image_labels | selectattr('key', '==', 'BUILD_COMMIT_ID') | map(attribute='value') | unique | join(',') }}"
          build_branch: "{{ image_labels | selectattr('key', '==', 'BUILD_COMMIT_ID') | map(attribute='value') | unique | join(',') }}"
      delegate_to: localhost
      become: false
      vars:
        image_labels: "{{ inspect_l.results | union(inspect_r.results | default([])) | map(attribute='stdout') | map('default','[]',true) | map('from_json') | flatten | map(attribute='Config') | map('default',[],true) | map(attribute='Labels') | map('default',{},true) | map('dict2items') | flatten }}"
      ignore_errors: true

    - name: cancel port forwarding
      shell:
        cmd: |
          ssh -p {{ ansible_port | default(22) }} {{ ansible_user }}@{{ ansible_host }} -i {{ ansible_private_key_file }} -O cancel -L {{ local_daemon_url }}:/var/run/docker.sock > /dev/null 2>&1
        executable: /bin/bash
      delegate_to: localhost
      become: false

