#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
AVC:
  description: 'x264 is very common. Different customers use x264 accross different presets. Measure acrsoss bookends common useage'
  group: >-
    AVC-1080p
AVC-1080p:
  description: 'Currently this is the same as AVC. Use "AVC" group until use for more modular grouping arises. '
  group: >-
    AVC-1080p-fast-avx2
    AVC-1080p-medium-avx2
    AVC-1080p-veryslow-avx2
AVC-fast:
  description: 'All the fast AVC tests'
  group: >-
    AVC-1080p-fast-avx2
AVC-medium:
  description: 'All the medium AVC tests'
  group: >-
    AVC-1080p-medium-avx2
AVC-veryslow:
  description: 'All the veryslow AVC tests'
  group: >-
    AVC-1080p-veryslow-avx2
AVC-avx2:
  description: 'All the avx2 AVC tests'
  group: >-
    AVC-1080p-fast-avx2
    AVC-1080p-medium-avx2
    AVC-1080p-veryslow-avx2


#All use cases#
# May need to place the preset in the args field
#------------AVC/x264 commands-----------------#
#    AVC-1080p-fast-avx2
#    AVC-1080p-medium-avx2
#    AVC-1080p-veryslow-avx2
AVC-1080p-fast-avx2:
  description: '1080p x264 encode prioritizing encode speed.'
  input_files: Mixed_40sec_1920x1080_60fps_8bit_420_crf23_veryslow.mp4
  input_format: 1080P-avx2
  output_mode:
    type: 1:1/LIVE
  video_codec:
    codec: x264
    preset: fast
    args: >-
      -x264-params "keyint=120:min-keyint=120:sliced-threads=0:scenecut=0:asm=avx2:threads=8" -tune psnr -profile:v high -b:v 6M -maxrate 12M -bufsize 24M -r 60  -y 1080p.mp4
AVC-1080p-medium-avx2:
  description: '1080p x264 encode balances speed and quality.'
  input_files: Mixed_40sec_1920x1080_60fps_8bit_420_crf23_veryslow.mp4
  input_format: 1080P-avx2
  output_mode:
    type: 1:1/LIVE
  video_codec:
    codec: x264
    preset: medium
    args: >-
       -x264-params "keyint=120:min-keyint=120:sliced-threads=0:scenecut=0:asm=avx2:threads=8" -tune psnr -profile:v high -b:v 6M -maxrate 12M -bufsize 24M -r 60  -y 1080p.mp4
#REAL TEST
AVC-1080p-veryslow-avx2:
  description: '1080p x264 encode prioritizing encode speed.'
  input_files: Mixed_40sec_1920x1080_60fps_8bit_420_crf23_veryslow.mp4
  input_format: 1080P-avx2
  output_mode:
    type: 1:1/LIVE
  video_codec:
    codec: x264
    preset: veryslow
    args: >-
      -x264-params "keyint=240:min-keyint=240:sliced-threads=0:scenecut=0:asm=avx2:threads=8" -tune psnr -profile:v high -b:v 5M -maxrate 10M -bufsize 20M -r 60  -y 1080p.mp4
