#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

### Gloabl Configuration ###
REGISTRY: ""
RELEASE: ""
PLATFORM: ""
BACKEND: ""
COLON: ":"

### Workload Configuration ###
DEBUG: false
WORKLOAD: "calicovpp"
TESTCASE: ""
SIMU: "trex"
HOSTNETWORK_ENABLE: true

#2048|1048576 corresponding 2M|1G
PER_HUGEPAGE_SIZE: 1048576
HUGEPAGES: 16
MTU: 1500
BUFFER_DATA_SIZE: "{{ if (int .MTU) eq 9000 }}10240{{ else }}2048{{ end }}"
CORE_SIZE: 1
ENABLE_DSA: false

### VPP ###
VPP_MEMIF_TCP_PORTS_RANGE: "4444-20000"
VPP_MEMIF_UDP_PORTS_RANGE: "4444-20000"
VPP_TUNTAP_PORTS_RANGE: "default"
VPP_CORE_START: 0
VPP_CORELIST_END: "{{ (int .VPP_CORE_START) | add (int .CORE_SIZE) }}"

### Trex ###
TREX_PACKET_SIZE: 102
TREX_DURATION: 29
TREX_SOURCE_IP: 182.168.126.19
TREX_STREAM_SIZE: 1
TREX_CORE_NUM: 8

# TREX_PCI_ID_1: "0000:99:00.0"
# DEST_MAC_1: "40:a6:b7:97:34:b0"
# TREX_MAC_ADDRESS: "40:a6:b7:97:33:00"
# TREX_PCI_ID_2: "dummy"
# DEST_MAC_2: "40:a6:b7:97:34:b0"
# TREX_MAC_ADDRESS: "40:a6:b7:97:33:00"

TREX_CPU_REQUESTS: 8
TREX_HUGEPAGES: 8

MASTER_THREAD_ID: 98
LATENCY_THREAD_ID: 99
TREX_THREADS: "10.101.102.103.104.105.106.107"
### L3fwd ###
L3FWD_CORE_START: 16