#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
- name: Check if istio installed
  shell:
    cmd: "which istioctl"
  ignore_errors: true
  register: istio_installed

- name: Uninstall istio
  become: true
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "istioctl uninstall --purge -y"
  when: istio_installed.rc == 0

- name: Delete istio-system secret nighthawk-credential
  command: "kubectl delete secret -n istio-system nighthawk-credential"
  ignore_errors: true

- name: Remove link of istioctl
  become: true
  file:
    path: "/usr/local/bin/istioctl"
    state: absent
  ignore_errors: true
  when: istio_installed.rc == 0

- name: Delete istioctl
  become: true
  file:
    path: "{{ istio_install_dir }}"
    state: absent
  ignore_errors: true
  when: istio_installed.rc == 0

- name: Delete istio-workload namespace
  command: "kubectl delete namespace {{ istio_injection_namespace }}"
  ignore_errors: true

- name: Delete istio-system namespace
  command: "kubectl delete namespace istio-system"
