#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# install calicovpp
k8s_calicovpp_version: "v3.23.0"
k8s_calicovpp_repository: "https://raw.githubusercontent.com/projectcalico/vpp-dataplane/{{k8s_calicovpp_version}}/yaml/generated/calico-vpp.yaml"

k8s_calivppctl_version: "v3.23.0"
# install calivppctl for calico vpp networking diagnose
k8s_calivppctl_repository: "https://raw.githubusercontent.com/projectcalico/vpp-dataplane/{{k8s_calivppctl_version}}/test/scripts/vppdev.sh"
k8s_calivppctl_install_dest: "/usr/local/bin/calivppctl"

# ip/network interface/pci_device_id bound by dpdk
k8s_calicovpp_network_mapping: "/etc/vpp-network-mapping.conf"

k8s_calicovpp_uplink_driver: "dpdk"

k8s_calicovpp_image_vpp_version: "v3.23.0"
k8s_calicovpp_image_agent_version: "v3.23.0"
k8s_calicovpp_image_vpp: "docker.io/calicovpp/vpp:{{k8s_calicovpp_image_vpp_version}}"
k8s_calicovpp_image_agent: "docker.io/calicovpp/agent:{{k8s_calicovpp_image_agent_version}}"
k8s_calicovpp_wait_ready_timeout: 60

k8s_calicovpp_buffer_data_size: 2048
k8s_calicovpp_cores: 1
k8s_calicovpp_core_start: 0
k8s_calicovpp_memif_enable: true


### DSA ###
k8s_calicovpp_dsa_enable: false
k8s_calicovpp_dsa_image_version: "latest"
k8s_calicovpp_dsa_image_vpp: "calicovpp_dsa_vpp"
k8s_calicovpp_dsa_image_agent: "calicovpp_dsa_agent"

### L3 Forward ###
k8s_calicovpp_l3fwd_enable: false
k8s_calicovpp_l3fwd_image: "calicovpp_l3fwd"
k8s_calicovpp_l3fwd_image_version: "latest"
k8s_calicovpp_l3fwd_protocol: "UDP"
k8s_calicovpp_l3fwd_port: 4444
k8s_calicovpp_l3fwd_memif_tcp_ports_range: "4444-20000"
k8s_calicovpp_l3fwd_memif_udp_ports_range: "4444-20000"
k8s_calicovpp_l3fwd_tuntap_ports_range: "default"
k8s_calicovpp_l3fwd_core_start: 16

k8s_calicovpp_l3fwd_neighbor_ip: "10.10.10.10"
k8s_calicovpp_l3fwd_packet_subnet_ip: "10.10.10.0/24"
k8s_calicovpp_l3fwd_mac: "10:00:00:00:00:00"

### TRex ###
k8s_calicovpp_trex_image: "calicovpp_trex"
k8s_calicovpp_trex_image_version: "latest"