#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- hosts: worker-0
  gather_facts: no
  tasks:
    - name: "Check if installation script exists"
      stat:
        path: /opt/workspace/template/ansible/custom/roles/dlb/tasks/driver_install.yaml
      register: check_install_script
      delegate_to: localhost

    - name: "Check if dlb driver already installed"
      shell: |
        ls -la /dev/dlb*
      ignore_errors: true
      register: dlb_driver_exist

    - name: Fail if DLB driver is not installed and install script not exist
      fail:
        msg: "Error: DLB driver is not installed and install script not exist"
      when: 
        - dlb_driver_exist.rc != 0
        - not check_install_script.stat.exists

    - name: "Install dlb driver"
      ansible.builtin.include_role:
        name: dlb
        tasks_from: driver_install.yaml
      when: 
        - wl_tunables['DLB_ACC'] == "enable"
        - dlb_driver_exist.rc != 0
        - check_install_script.stat.exists
        
- hosts: worker-1
  gather_facts: no
  tasks:
    - name: "Copy softirq binding scripts set_irq_affinity.sh to worker-1"
      ansible.builtin.include_role:
        name: prepare_system
        tasks_from: copy_scripts.yaml

    - name: Bind softirq on worker-1
      become: true
      shell:
        cmd: |
          /tmp/{{ wl_namespace }}-set_irq_affinity.sh --ip {{ hostvars['worker-1'].private_ip }} --cpu {{ wl_tunables.CONTENT_SERVER_CORE }}
        executable: /bin/bash

    - name: Delete set_irq_affinity.sh on worker-1
      become: true
      file:
        path: "/tmp/{{ wl_namespace }}-set_irq_affinity.sh"
        state: absent
      ignore_errors: true

- hosts: client-0
  gather_facts: no
  tasks:
    - name: "Copy softirq binding scripts set_irq_affinity.sh to client-0"
      ansible.builtin.include_role:
        name: prepare_system
        tasks_from: copy_scripts.yaml

    - name: Bind softirq on client-0
      become: true
      shell:
        cmd: |
          /tmp/{{ wl_namespace }}-set_irq_affinity.sh --ip {{ hostvars['client-0'].private_ip }} --cpu {{ wl_tunables.WRK_CORE }}
        executable: /bin/bash

    - name: Delete set_irq_affinity.sh on client-0
      become: true
      file:
        path: "/tmp/{{ wl_namespace }}-set_irq_affinity.sh"
        state: absent
      ignore_errors: true

- hosts: controller-0
  gather_facts: no
  tasks:
    - name: "Apply kubernetes DLB device plugin"
      ansible.builtin.include_role:
        name: dlb
        tasks_from: kubernetes_plugin_apply.yaml
      when: 
        - wl_tunables['DLB_ACC'] == "enable"

- hosts: localhost
  gather_facts: no
  tasks: 
    - name: "Patch kubernetes config for cache server ip"
      shell: sed -i 's|CACHE_SERVER_IP_REPLACE|{{ hostvars['worker-0'].private_ip }}|' {{ wl_logs_dir }}/kubernetes-config.yaml
    - name: "Patch kubernetes config for content server ip"
      shell: sed -i 's|CONTENT_SERVER_IP_REPLACE|{{ hostvars['worker-1'].private_ip }}|' {{ wl_logs_dir }}/kubernetes-config.yaml