#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Uninstall Istio if installed
  include_role:
    name: istio
    tasks_from: uninstall
  when:
  - k8s_istio_profile is defined
  - k8s_istio_profile | trim != ""
