#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# install calico vpp network diagnose tools
- name: Check if calivppctl installed
  become: true
  ansible.builtin.stat:
    path: "{{ k8s_calivppctl_install_dest }}"
  register: check_file
  
- name: Download calivppctl 
  become: true
  get_url:
    url: "{{ k8s_calivppctl_repository }}"
    dest: "{{ k8s_calivppctl_install_dest }}"
    mode: +rx
  when: not check_file.stat.exists