#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Replace l3fwd pod ip
  include_role: 
    name: cni-calicovpp
    tasks_from: replace-l3fwd-pod-ip.yaml
  when: k8s_cni == "calicovpp"
