#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


- name: Get mac address by network interface name
  become: true
  shell: "ethtool -P {{ vpp_dataplane_interface }} |awk -F 'Permanent address: ' '{print $2}'"
  ignore_errors: true
  register: get_mac_address

- name: Backout mac address if changed
  become: true
  shell: |
    macchanger -m {{ vpp_dataplane_mac_address }} {{ vpp_dataplane_interface }}
  ignore_errors: true
  when: vpp_dataplane_mac_address != get_mac_address.stdout