#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove calico common
  include_role:
    name: cni-calico
    tasks_from: reset.yaml

- name: Address mac address change
  include_tasks:
    file: rescue-macchange.yaml

- name: Unbind devices
  include_tasks:
    file: unbind.yaml

- name: Network mapping
  include_tasks:
    file: network-mapping.yaml

- name: save customized calicovpp images
  become: true
  shell: |
    docker save {{ k8s_calicovpp_dsa_image_vpp }}{{ k8s_calicovpp_dsa_image_version | default('latest') }} > /tmp/{{ wl_namespace }}_calicovpp_dsa_vpp.tar
    docker save {{ k8s_calicovpp_dsa_image_agent }}{{ k8s_calicovpp_dsa_image_version | default('latest') }} > /tmp/{{ wl_namespace }}_calicovpp_dsa_agent.tar
  delegate_to: localhost
  when: k8s_calicovpp_dsa_enable | default(false)

- name: save wl_docker_images
  become: true
  shell: |
    docker save {{ k8s_calicovpp_l3fwd_image }}{{ k8s_calicovpp_l3fwd_image_version | default('latest') }} > /tmp/{{ wl_namespace }}_calicovpp_l3fwd.tar
    docker save {{ k8s_calicovpp_trex_image }}{{ k8s_calicovpp_trex_image_version | default('latest') }} > /tmp/{{ wl_namespace }}_calicovpp_trex.tar
  delegate_to: localhost

- name: copy customized calicovpp images to remote 
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src:  "/tmp/{{ wl_namespace }}_calicovpp_dsa_vpp.tar"
      dest: "/tmp/{{ wl_namespace }}_calicovpp_dsa_vpp.tar"
    - src: "/tmp/{{ wl_namespace }}_calicovpp_dsa_agent.tar"
      dest: "/tmp/{{ wl_namespace }}_calicovpp_dsa_agent.tar"
  when: k8s_calicovpp_dsa_enable | default(false)

- name: copy wl_docker_images to remote 
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "/tmp/{{ wl_namespace }}_calicovpp_l3fwd.tar"
      dest: "/tmp/{{ wl_namespace }}_calicovpp_l3fwd.tar"
    - src: "/tmp/{{ wl_namespace }}_calicovpp_trex.tar"
      dest: "/tmp/{{ wl_namespace }}_calicovpp_trex.tar"

- name: ctr import calicovpp images
  become: true
  shell: |
    ctr -n=k8s.io images import {{ item }}
  loop:
    - /tmp/{{ wl_namespace }}_calicovpp_dsa_vpp.tar
    - /tmp/{{ wl_namespace }}_calicovpp_dsa_agent.tar
  when: k8s_calicovpp_dsa_enable | default(false)

- name: ctr import wl_docker_images
  become: true
  shell: |
    ctr -n=k8s.io images import {{ item }}
  loop:
    - /tmp/{{ wl_namespace }}_calicovpp_l3fwd.tar
    - /tmp/{{ wl_namespace }}_calicovpp_trex.tar

- name: remove localhost image files
  become: true
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /tmp/{{ wl_namespace }}_calicovpp_dsa_vpp.tar
    - /tmp/{{ wl_namespace }}_calicovpp_dsa_agent.tar
    - /tmp/{{ wl_namespace }}_calicovpp_l3fwd.tar
    - /tmp/{{ wl_namespace }}_calicovpp_trex.tar
  delegate_to: localhost

- name: remove remote image files
  become: true
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /tmp/{{ wl_namespace }}_calicovpp_dsa_vpp.tar
    - /tmp/{{ wl_namespace }}_calicovpp_dsa_agent.tar
    - /tmp/{{ wl_namespace }}_calicovpp_l3fwd.tar
    - /tmp/{{ wl_namespace }}_calicovpp_trex.tar
