#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- block:

  - name: "Create start-trace.sh on {{ trace_host }}"
    template:
      src: "start-trace.sh.j2"
      dest: "/tmp/{{ wl_namespace }}-{{ trace_host }}-start-trace.sh"
      mode: "a+rx"

  - name: "Create stop-trace.sh on {{ trace_host }}"
    template:
      src: "stop-trace.sh.j2"
      dest: "/tmp/{{ wl_namespace }}-{{ trace_host }}-stop-trace.sh"
      mode: "a+rx"

  - name: set flag to prevent multiple installations
    set_fact:
      trace_script_installed: true
    delegate_facts: true

  when: not (hostvars[trace_host].trace_script_installed | default(false))
  delegate_to: "{{ trace_host }}"
