#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
- name: Get host ip of controller-0
  set_fact:
    controller_host_ip: '{{ hostvars["controller-0"]["private_ip"] }}'

- name: Get hostname of worker
  shell: "kubectl get node -owide|grep {{ controller_host_ip }}|awk '{print $1}'"
  register: controller_host_name

- name: Patch k8s config kubernetes-config.yaml - Change nodeselector to specified hostname
  command: "sed  -i 's|${ISTIO_ENVOY_CLIENT_HOSTNAME}|{{ controller_host_name.stdout }}|' ../../../kubernetes-config.yaml"
  delegate_to: localhost